/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BottomNavbar: typeof import('./../components/BottomNavbar.vue')['default']
    BottomNavbarNew: typeof import('./../components/BottomNavbarNew.vue')['default']
  }
}
